# Generated by Django 2.2 on 2020-08-22 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12_app', '0003_auto_20200822_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 21, 49, 26, 573278)),
        ),
    ]
